### ISSUE TITLE
[Azure Service Bus] Components do not recover from failures when publishing

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#2483]
## Description

Issue reported on Discord: https://discord.com/channels/778680217417809931/1067897796725841930

Seems that after publishing fails on Azure Service Bus with a connection error, the connection enters in a "bad" state and Dapr isn't able to recover from it.

We have some code in place that forces a reconnection if the subscribing connection gets into a "bad" state. However we have nothing in place that causes the connection to be recreated if the publishing side continues to fail.

## Release Note

RELEASE NOTE: **FIX** Force reconnecting to Azure Service Bus after a persistent publish failure

**Comment by ItalyPaleAle** [comment]
Fixed in release-1.10

**Comment by jgquiroga** [comment]
Hi. We are using Dapr 1.10.9 with Azure Service Bus (Standard) and this error continues to appear at random times.

Our system runs in Azure AKS with Kubernetes 1.25.1

It doesn't appear in lower environments. It appears in Production environments. The difference seems to be that in production we have messages that are very large.
For this specific application, the clients don't use the system on weekends. So, it seems to be related with some inactivity time. Once we receive this error, we have this problem:
Because it tries to retry 5 times every 5 seconds, the app that is publishing the message is waiting 36.1 seconds. And then it receives the error:

{
    "app_id":"test-component-stage01",
    "component":"stage01-execution-pubsub (pubsub.azure.servicebus/v1)",
    "instance":"test-component-stage01-in-64b54fb847-lksdk",
    "level":"error",
    "msg":"Too many failed attempts while publishing Service Bus message (nil): context deadline exceeded",
    "scope":"dapr.contrib",
    "time":"2023-09-06T01:00:58.249883081Z",
    "type":"log",
    "ver":"1.10.9"
}

The solution that we found right now is :

- Duplicate the service bus component and send the same message to the other pubsub.
- Add a flag indicating that bus 1 is broken and call the bus 2
- Make an alert to recycle the pod

For example: 
"test-component-stage-01"  => the principal one
"test-component-stage-01-failover"  => the secondary one

(both components points to the same topic in service bus) Because they have different keys in dapr, they have different Senders.
In the same pod, The first one is taking 36.1 seconds and the second one a couple of milliseconds.

- Later, we are going to try to put an Unhealthy flag in our health checks so Kubernetes can recycle the pod automatically.


[https://github.com/ItalyPaleAle/dapr-components-contrib/blob/master/internal/component/azure/servicebus/publisher.go#L63](https://github.com/ItalyPaleAle/dapr-components-contrib/blob/master/internal/component/azure/servicebus/publisher.go#L63)

If I am not wrong, recycling the Sender should be enough to make it work again, as the Line 63 says. 

But because I see that it is retrying, I think it is going to the line: IsRetriableAMQPError that doesn't recycle the Sender.

We also have this in the logs:
---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="error when publish to topic test-component-stage01 in pubsub stage01-execution-pubsub: context deadline exceeded")

We are setting the logs in Debug to see if we can get more information. 

I think a Debug log should appear to indicate that the error was or type Network or RetriableAMQP to see what is the condition used.

Thank you.

**Comment by jgquiroga** [comment]
I have and update on this. 

This is the log:
```
{"app_id":"test-component-stage01","component":"test-component-pubsub (pubsub.azure.servicebus/v1)","instance":"test-component-stage01-in-544896f7d-l7qk8","level":"debug","msg":"Closed sender: stage01-integration-events-execution-connectors-resume-execution-command","scope":"dapr.contrib","time":"2023-09-07T12:48:21.843501352Z","type":"log","ver":"1.10.9"}
{"app_id":"test-component-stage01","component":"test-component-pubsub (pubsub.azure.servicebus/v1)","instance":"test-component-stage01-in-544896f7d-l7qk8","level":"info","msg":"Closing sender: stage01-integration-events-execution-connectors-resume-execution-command","scope":"dapr.contrib","time":"2023-09-07T12:48:21.843569357Z","type":"log","ver":"1.10.9"}
{"app_id":"test-component-stage01","component":"test-component-pubsub (pubsub.azure.servicebus/v1)","instance":"test-component-stage01-in-544896f7d-l7qk8","level":"error","msg":"Too many failed attempts while publishing Service Bus message (nil): context deadline exceeded","scope":"dapr.contrib","time":"2023-09-07T12:48:22.133464598Z","type":"log","ver":"1.10.9"}
{"app_id":"test-component-stage01","instance":"test-component-stage01-in-544896f7d-l7qk8","level":"debug","msg":"rpc error: code = Internal desc = error when publish to topic stage01-integration-command in pubsub test-component-pubsub: context deadline exceeded","scope":"dapr.runtime.grpc.api","time":"2023-09-07T12:48:22.133562604Z","type":"log","ver":"1.10.9"}
```

I am seeing that the "Sender" is already being closed but the sidecar still doesn't work.

I was able to reproduce this issue in a unit test calling the publish method in parallel and with 262100 bytes
value := make([]byte, 262100)

One of the things I detected is that the Sender should be closed by instance and not by getting a sender from the current list.

This 
```
c.CloseSender(sender, req.Topic, log)
```

Instead of this:
```
c.CloseSender(req.Topic, log)
```

What is happeining is that another process got an error so it already closed the connection and created a new one
